import MixerScoreScroller from '@/app/ui/competitions/mixer/mixer-score-scroller';

const mixerRoutes = [
  {
    id: 0,
    routeName: 'Route A',
    holds: [
      { holdNumber: 1, topRopePoints: 1, leadPoints: 2 },
      { holdNumber: 2, topRopePoints: 4, leadPoints: 6 },
      { holdNumber: 3, topRopePoints: 7, leadPoints: 11 },
      { holdNumber: 4, topRopePoints: 10, leadPoints: 15 },
      { holdNumber: 5, topRopePoints: 13, leadPoints: 20 },
      { holdNumber: 6, topRopePoints: 17, leadPoints: 25 },
      { holdNumber: 7, topRopePoints: 21, leadPoints: 30 },
      { holdNumber: 8, topRopePoints: 24, leadPoints: 34 },
      { holdNumber: 9, topRopePoints: 28, leadPoints: 38 },
      { holdNumber: 10, topRopePoints: 32, leadPoints: 45 },
      { holdNumber: 11, topRopePoints: 35, leadPoints: 48 },
      { holdNumber: 12, topRopePoints: 37, leadPoints: 54 },
      { holdNumber: 13, topRopePoints: 43, leadPoints: 59 },
      { holdNumber: 14, topRopePoints: 47, leadPoints: 64 },
      { holdNumber: 15, topRopePoints: 49, leadPoints: 67 },
      { holdNumber: 16, topRopePoints: 53, leadPoints: 70 },
      { holdNumber: 17, topRopePoints: 56, leadPoints: 74 },
      { holdNumber: 18, topRopePoints: 61, leadPoints: 77 },
    ],
    color: 'blue',
  },
  {
    id: 1,
    routeName: 'Route B',
    holds: [
      { holdNumber: 1, topRopePoints: 3, leadPoints: 5 },
      { holdNumber: 2, topRopePoints: 9, leadPoints: 14 },
      { holdNumber: 3, topRopePoints: 16, leadPoints: 23 },
      { holdNumber: 4, topRopePoints: 22, leadPoints: 33 },
      { holdNumber: 5, topRopePoints: 31, leadPoints: 44 },
      { holdNumber: 6, topRopePoints: 36, leadPoints: 52 },
      { holdNumber: 7, topRopePoints: 46, leadPoints: 63 },
      { holdNumber: 8, topRopePoints: 51, leadPoints: 69 },
      { holdNumber: 9, topRopePoints: 60, leadPoints: 75 },
      { holdNumber: 10, topRopePoints: 66, leadPoints: 84 },
      { holdNumber: 11, topRopePoints: 72, leadPoints: 88 },
      { holdNumber: 12, topRopePoints: 75, leadPoints: 93 },
      { holdNumber: 13, topRopePoints: 83, leadPoints: 100 },
      { holdNumber: 14, topRopePoints: 86, leadPoints: 103 },
      { holdNumber: 15, topRopePoints: 90, leadPoints: 106 },
      { holdNumber: 16, topRopePoints: 92, leadPoints: 109 },
      { holdNumber: 17, topRopePoints: 97, leadPoints: 114 },
    ],
    color: 'green',
  },
  {
    id: 2,
    routeName: 'Route C',
    holds: [
      { holdNumber: 1, topRopePoints: 8, leadPoints: 12 },
      { holdNumber: 2, topRopePoints: 18, leadPoints: 26 },
      { holdNumber: 3, topRopePoints: 29, leadPoints: 40 },
      { holdNumber: 4, topRopePoints: 39, leadPoints: 55 },
      { holdNumber: 5, topRopePoints: 50, leadPoints: 68 },
      { holdNumber: 6, topRopePoints: 62, leadPoints: 79 },
      { holdNumber: 7, topRopePoints: 71, leadPoints: 87 },
      { holdNumber: 8, topRopePoints: 78, leadPoints: 95 },
      { holdNumber: 9, topRopePoints: 85, leadPoints: 102 },
      { holdNumber: 10, topRopePoints: 91, leadPoints: 108 },
      { holdNumber: 11, topRopePoints: 96, leadPoints: 113 },
      { holdNumber: 12, topRopePoints: 101, leadPoints: 118 },
      { holdNumber: 13, topRopePoints: 107, leadPoints: 124 },
      { holdNumber: 14, topRopePoints: 110, leadPoints: 126 },
      { holdNumber: 15, topRopePoints: 116, leadPoints: 132 },
      { holdNumber: 16, topRopePoints: 117, leadPoints: 136 },
      { holdNumber: 17, topRopePoints: 123, leadPoints: 140 },
      { holdNumber: 18, topRopePoints: 125, leadPoints: 142 },
      { holdNumber: 19, topRopePoints: 128, leadPoints: 146 },
      { holdNumber: 20, topRopePoints: 131, leadPoints: 147 },
      { holdNumber: 21, topRopePoints: 133, leadPoints: 149 },
    ],
    color: 'orange',
  },
  {
    id: 3,
    routeName: 'Route D',
    holds: [
      { holdNumber: 1, topRopePoints: 19, leadPoints: 27 },
      { holdNumber: 2, topRopePoints: 42, leadPoints: 58 },
      { holdNumber: 3, topRopePoints: 65, leadPoints: 82 },
      { holdNumber: 4, topRopePoints: 81, leadPoints: 99 },
      { holdNumber: 5, topRopePoints: 94, leadPoints: 111 },
      { holdNumber: 6, topRopePoints: 105, leadPoints: 122 },
      { holdNumber: 7, topRopePoints: 115, leadPoints: 130 },
      { holdNumber: 8, topRopePoints: 121, leadPoints: 139 },
      { holdNumber: 9, topRopePoints: 127, leadPoints: 145 },
      { holdNumber: 10, topRopePoints: 135, leadPoints: 151 },
      { holdNumber: 11, topRopePoints: 141, leadPoints: 156 },
      { holdNumber: 12, topRopePoints: 144, leadPoints: 161 },
      { holdNumber: 13, topRopePoints: 148, leadPoints: 164 },
      { holdNumber: 14, topRopePoints: 155, leadPoints: 169 },
      { holdNumber: 15, topRopePoints: 157, leadPoints: 173 },
      { holdNumber: 16, topRopePoints: 160, leadPoints: 176 },
      { holdNumber: 17, topRopePoints: 162, leadPoints: 178 },
      { holdNumber: 18, topRopePoints: 166, leadPoints: 182 },
      { holdNumber: 19, topRopePoints: 170, leadPoints: 184 },
      { holdNumber: 20, topRopePoints: 172, leadPoints: 187 },
    ],
    color: 'yellow',
  },
  {
    id: 4,
    routeName: 'Route E',
    holds: [
      { holdNumber: 1, topRopePoints: 41, leadPoints: 57 },
      { holdNumber: 2, topRopePoints: 80, leadPoints: 98 },
      { holdNumber: 3, topRopePoints: 104, leadPoints: 120 },
      { holdNumber: 4, topRopePoints: 119, leadPoints: 138 },
      { holdNumber: 5, topRopePoints: 134, leadPoints: 150 },
      { holdNumber: 6, topRopePoints: 143, leadPoints: 159 },
      { holdNumber: 7, topRopePoints: 154, leadPoints: 168 },
      { holdNumber: 8, topRopePoints: 158, leadPoints: 175 },
      { holdNumber: 9, topRopePoints: 165, leadPoints: 181 },
      { holdNumber: 10, topRopePoints: 171, leadPoints: 186 },
      { holdNumber: 11, topRopePoints: 177, leadPoints: 191 },
      { holdNumber: 12, topRopePoints: 180, leadPoints: 195 },
      { holdNumber: 13, topRopePoints: 185, leadPoints: 199 },
      { holdNumber: 14, topRopePoints: 190, leadPoints: 202 },
      { holdNumber: 15, topRopePoints: 192, leadPoints: 205 },
      { holdNumber: 16, topRopePoints: 194, leadPoints: 208 },
      { holdNumber: 17, topRopePoints: 197, leadPoints: 210 },
      { holdNumber: 18, topRopePoints: 200, leadPoints: 212 },
      { holdNumber: 19, topRopePoints: 204, leadPoints: 215 },
    ],
    color: 'red',
  },
  {
    id: 5,
    routeName: 'Route F',
    holds: [
      { holdNumber: 1, topRopePoints: 73, leadPoints: 89 },
      { holdNumber: 2, topRopePoints: 112, leadPoints: 129 },
      { holdNumber: 3, topRopePoints: 137, leadPoints: 153 },
      { holdNumber: 4, topRopePoints: 152, leadPoints: 167 },
      { holdNumber: 5, topRopePoints: 163, leadPoints: 179 },
      { holdNumber: 6, topRopePoints: 174, leadPoints: 189 },
      { holdNumber: 7, topRopePoints: 183, leadPoints: 196 },
      { holdNumber: 8, topRopePoints: 188, leadPoints: 201 },
      { holdNumber: 9, topRopePoints: 193, leadPoints: 207 },
      { holdNumber: 10, topRopePoints: 198, leadPoints: 211 },
      { holdNumber: 11, topRopePoints: 203, leadPoints: 214 },
      { holdNumber: 12, topRopePoints: 206, leadPoints: 218 },
      { holdNumber: 13, topRopePoints: 209, leadPoints: 220 },
      { holdNumber: 14, topRopePoints: 213, leadPoints: 222 },
      { holdNumber: 15, topRopePoints: 216, leadPoints: 225 },
      { holdNumber: 16, topRopePoints: 217, leadPoints: 227 },
      { holdNumber: 17, topRopePoints: 219, leadPoints: 229 },
      { holdNumber: 18, topRopePoints: 221, leadPoints: 230 },
      { holdNumber: 19, topRopePoints: 223, leadPoints: 231 },
      { holdNumber: 20, topRopePoints: 224, leadPoints: 232 },
      { holdNumber: 21, topRopePoints: 226, leadPoints: 233 },
      { holdNumber: 22, topRopePoints: 228, leadPoints: 234 },
    ],
    color: 'red',
  },
];

export default function Mixer() {
  return (
    <>
      <MixerScoreScroller mixerRoutes={mixerRoutes} StartTime={null} />
    </>
  );
}
